# Generated by Django 3.2 on 2021-05-06 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='foodform',
            name='price',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
