# Generated by Django 3.2 on 2021-05-09 02:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0002_foodform_price'),
    ]

    operations = [
        migrations.DeleteModel(
            name='foodForm',
        ),
        migrations.RemoveField(
            model_name='menuitem',
            name='category',
        ),
        migrations.RemoveField(
            model_name='ordermodel',
            name='items',
        ),
        migrations.DeleteModel(
            name='Category',
        ),
        migrations.DeleteModel(
            name='MenuItem',
        ),
        migrations.DeleteModel(
            name='OrderModel',
        ),
    ]
