# Generated by Django 3.2 on 2021-05-09 08:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0004_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ordermodel',
            name='items',
        ),
        migrations.DeleteModel(
            name='foodForm',
        ),
        migrations.DeleteModel(
            name='OrderModel',
        ),
        migrations.DeleteModel(
            name='Style',
        ),
    ]
