# Generated by Django 3.2 on 2021-05-09 09:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('customer', '0005_auto_20210509_1555'),
    ]

    operations = [
        migrations.CreateModel(
            name='foodForm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('nguyenlieu', models.TextField()),
                ('soche', models.TextField()),
                ('thuchien', models.TextField()),
                ('cachdung', models.TextField()),
                ('machnho', models.TextField()),
                ('image', models.ImageField(upload_to='menu_id/')),
                ('video', models.TextField()),
                ('price', models.DecimalField(decimal_places=3, max_digits=7)),
            ],
        ),
        migrations.CreateModel(
            name='Style',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='OrderModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('price', models.DecimalField(decimal_places=3, max_digits=7)),
                ('items', models.ManyToManyField(blank=True, related_name='oder', to='customer.foodForm')),
            ],
        ),
        migrations.AddField(
            model_name='foodform',
            name='loai',
            field=models.ManyToManyField(related_name='item', to='customer.Style'),
        ),
    ]
