# Generated by Django 3.2 on 2021-05-15 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0007_auto_20210515_2029'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ordermodel',
            name='SDT',
        ),
        migrations.AlterField(
            model_name='ordermodel',
            name='items',
            field=models.ManyToManyField(blank=True, related_name='order', to='customer.foodForm'),
        ),
    ]
