# Generated by Django 3.2 on 2021-05-15 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0008_auto_20210515_2155'),
    ]

    operations = [
        migrations.AddField(
            model_name='ordermodel',
            name='SDT',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
