# Generated by Django 3.2 on 2021-05-17 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0009_ordermodel_sdt'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='foodform',
            options={'verbose_name': 'foodForm', 'verbose_name_plural': 'foodForms'},
        ),
        migrations.AlterField(
            model_name='foodform',
            name='video',
            field=models.FileField(upload_to='video/'),
        ),
    ]
