# Generated by Django 3.2 on 2021-05-18 03:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0010_auto_20210517_2215'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ordermodel',
            name='items',
            field=models.ManyToManyField(related_name='order', to='customer.foodForm'),
        ),
    ]
