# Generated by Django 3.2 on 2021-05-06 05:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0004_auto_20210503_1520'),
    ]

    operations = [
        migrations.CreateModel(
            name='foodForm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('nguyenlieu', models.TextField()),
                ('soche', models.TextField()),
                ('thuchien', models.TextField()),
                ('cachdung', models.TextField()),
                ('machnho', models.TextField()),
                ('image', models.TextField()),
                ('video', models.TextField()),
                ('create_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
